language: php

php:
  - 5.6
  - 7.2
  - 7.3

env: 
  - SYMFONY_VERSION=^2.8
  - SYMFONY_VERSION=^3.4
  - SYMFONY_VERSION=^4.2

cache:
    directories:
        - $HOME/.composer/cache

matrix:
  exclude:
    php: 5.6
    env: SYMFONY_VERSION=^4.2

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini || true
  - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION} symfony/form:${SYMFONY_VERSION}

install: composer update --prefer-dist

script: vendor/bin/phpunit

notifications:
  email:
    - damien.matabon@gmail.com
